### ISSUE TITLE
[Sandbox] Subscription renewal orders are marked as Failed

### ISSUE THREAD

**Issue by AashikP** [woocommerce/woocommerce-gateway-payfast#73]
### Describe the Bug

Subscription renewal orders are marked as Failed incorrectly. The Subscription itself is set to Active, but a second ITN sets the order status to Failed, causing confusion while checking the order notes.

### To Reproduce

*   Place a Subscription order - This goes through successfully
*   Try `Process renewal` action on the Subscription
*   Notice that Subscription itself is not marked as failed, but the order is marked as paid first, and then set to failed
    
*   Subscription notes:
    
    ![https://d.pr/i/9Hrl1A+](https://d.pr/i/9Hrl1A+)
    
*   Order notes:
    
    ![https://d.pr/i/1XTsNY+](https://d.pr/i/1XTsNY+)
    
*   Try to re-submit ITN from Payfast:
    
    ![https://d.pr/i/sKVkSW+](https://d.pr/i/sKVkSW+)
    
*   Notice that the order is now set to processing:
    
    ![https://d.pr/i/f2I8Zu+](https://d.pr/i/f2I8Zu+)
    
*   No change on the Subscription except for the update to order status:
    
    ![https://d.pr/i/Fra3K9+](https://d.pr/i/Fra3K9+)

### Expected Behavior

For the system tp prevent marking the order as failed once it is already marked as paid for.

### Actual Behavior

As of now the system is first marking the order as paid, setting the Subscription status to active, and then marking the order as failed again.

### Environment

 - *WordPress Version* 5.9.2
 - *WooCommerce Version* 6.3.1
 - *Plugin Version* 1.4.20
 - *Browser [e.g. Chrome, Safari] and Version* Any
 - *Any other plugins installed* N/A

### Additional Details

**Customer Reports**: 4844879-zen

**Comment by iamdharmesh** [comment]
Hi @AashikP, 

Thanks for reporting the issue. I came across this issue during the implementation of #32, So, I already fixed this under PR https://github.com/woocommerce/woocommerce-gateway-payfast/pull/63.

@dkotter @jeffpaul moving this to QA directly.

Thanks.

**Comment by ankitguptaindia** [comment]
**Update -**  Above issue(s) have been fixed with connected PR. New customers' reports of this issue can be tested/verify with this **Development version** of the plugin.

[woocommerce-gateway-payfast.zip](https://github.com/woocommerce/woocommerce-gateway-payfast/files/8652067/woocommerce-gateway-payfast.zip)



**_Please Note that this is Dev version of the plugin file and ONLY has fixes related to the above issue so other fixes might not work with this dev version of the plugin. It is also recommended that, Don't use this plugin file on the Production/Live site. This is just for testing purposes only_**
